version: '2.1'
volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local
  redis-data:
    driver: local
  rails-tmp:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
     - "3000:3000"
    links:
      - postgres
      - redis
    environment:
      - RACK_ENV=test
      - DATABASE_URL=postgres://postgres:contakti@postgres:5432/contakti
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.test
    volumes:
      - .:/app
      - app-gems:/usr/local/bundle
      - rails-tmp:/app/tmp
  postgres:
    image: "postgres:9.5-alpine"
    environment:
      POSTGRES_DB: contakti
      POSTGRES_PASSWORD: contakti
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
