development:
  host: localhost
  port: 6379
  namespace: '/danthes'

test:
  host: localhost
  port: 6379
  namespace: '/danthes'

production:
  server: <%= ENV["DANTHES_REDIS_SERVER"] %>
  port: 6379
  #password: redis_password
  #database: redis_database
  namespace: '/danthes'

staging:
  server: <%= ENV["DANTHES_REDIS_SERVER"] %>
  port: 6379
  #password: redis_password
  #database: redis_database
  namespace: '/danthes'
